#!/bin/dash

if test ! $# -eq 0
then 
    echo "Usage: $0"
    exit 1
fi

repo=.tigger
if test ! -d "$repo"
then 
    echo "$0: error: tigger repository directory $repo not found" >&2
    exit 1
fi 

current_branch=$(cat "$repo"/.current_branch)

cat $repo/branch/"$current_branch"/.log | sort -nr
